{% set name = "Hapi" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Hapi/archive/{{ version }}.tar.gz
  sha256: 490fbd56a786153c3cdc38f31f10ab1b5fc845499dd157c0da355c35dbcf5655

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python >=3.9,<3.15
    - pip >=22.3.1
  run:
    - python >=3.9,<3.15
    - numpy >=1.23.5
    - pip >=22.3.1
    - gdal >=3.5.3
    - pandas >=1.4.4
    - geopandas >=0.12.2
    - matplotlib >=3.5.3
    - scipy >=1.9.1
    - statsmodels >=0.13.2
    - rasterio >=1.3.2
    - rasterstats >=0.17.0
    - Fiona >=1.8.21
    - geostatista >=0.1.4
    - statista >=0.1.7
    - pyramids >=0.2.10
    - earth2observe >=0.1.6
    - Oasis >=1.0.2
    - digitalearth >=0.1.9
    - loguru >=0.6.0
    - pytest >=7.1.3
    - pytest-cov ==4.0.0
    - requests >=2.28.1

    
test:
  imports:
    - Hapi

about:
  home: https://github.com/MAfarrag/HAPI
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  license_file: LICENSE.md
  summary: Distributed Hydrological model
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://hapi-hm.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md

extra:
  recipe-maintainers:
    - MAfarrag
