{% set name = "Hapi" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Hapi/archive/{{ version }}.tar.gz
  sha256: 8f04138ab40581f4e0bdeb2ff5bd3f5295d9beec7daea78c576cbd47476b8d74

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  host:
    - python >=2.6
    - pip
  run:
    - python >=2.6
    - pip
    - numpy
    - affine
    - fiona
    - proj
    - pyproj
    - gdal
    - pandas
    - geopandas
    - matplotlib-base
    - python
    - scipy
    - shapely
    - statsmodels
    - rasterio
    - rasterstats
    - netCDF4
    - scikit-learn
    - scikit-image
    - ecmwf-api-client
    - oasis
    - joblib

test:
  imports:
    - Hapi
    
about:
  home: https://github.com/MAfarrag/HAPI
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Distributed Hydrological model'
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://hapi-hm.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md

extra:
  recipe-maintainers:
    - MAfarrag
