{% set name = "Hapi" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Hapi/archive/{{ version }}.tar.gz
  sha256: 72fc941e87dfaf0c35d7fde1b18bb8212f49df3dc757a9e4047291819138652a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python >=3.7
    - pip
  run:
    - pip >=21.3.1
    - numpy >=1.21.2,<1.22.3
    - gdal >=3.3.3,<3.4.2
    - affine >=2.3.0
    - fiona >=1.8.20
    - proj >=0.2.0
    - pyproj >=3.2.1,<=3.3.0
    - pandas >=1.3.2,<1.4.2
    - geopandas >=0.10.2
    - matplotlib >=3.4.2,<3.6.0
    - python >=3.7.1,<3.10
    - scipy >=1.7.0,<1.8.1
    - shapely >=1.8.0
    - statsmodels >=0.12.2,<0.14.0
    - rasterio >=1.2.10
    - rasterstats >=0.16.0
    - oasis >=0.1.3
    - netCDF4 >=1.5.5,<1.5.9
    - scikit-learn >=0.24.2,<1.0.2
    - scikit-image >=0.18.3
    - ecmwf-api-client >=1.6.1
    - joblib >=1.1.0
    - geopy >=2.2.0
    - loguru >=0.6.0
    - pytest >=6.2.5
    - pytest-cov >=2.12.1
test:
  imports:
    - Hapi

about:
  home: https://github.com/MAfarrag/HAPI
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  license_file: LICENSE.md
  summary: Distributed Hydrological model
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://hapi-hm.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md

extra:
  recipe-maintainers:
    - MAfarrag
