{% set name = "Hapi" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Hapi/archive/{{ version }}.tar.gz
  sha256: c0365cfda816b61d399b40fc575a110c62d38b76a32e0ac4024e73c8dc3e1d37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python >=3.9
    - pip >= 22.2.2
  run:
    - pip>=22.2.2
    - numpy>=1.21.2,<1.23.3
    - gdal>=3.3.3,<3.5.1
    - pyramids >= 0.2.0
    - pandas>=1.3.2,<1.5.0
    - Rtree>=0.9.4
    - geopandas>=0.10.2
    - matplotlib>=3.4.2,<3.6.0
    - scipy>=1.7.0,<1.8.1
    - statsmodels>=0.14.0
    - rasterstats>=0.16.0
    - oasis>=1.0.2
    - statista>=0.1.0
    - loguru>=0.5.3
    
test:
  imports:
    - Hapi

about:
  home: https://github.com/MAfarrag/HAPI
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  license_file: LICENSE.md
  summary: Distributed Hydrological model
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://hapi-hm.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md

extra:
  recipe-maintainers:
    - MAfarrag
